### ISSUE TITLE
Pesbuk can't reach Facebook anymore

### ISSUE THREAD

**Issue by Emphrath** [kugiigi/pesbuk-app#19]
Device

FP2
Stable
16.04 OTA-12

Steps to Reproduce

1. Open app
2. Wait for facebook to show up 
3. Close app

Expected Result

Facebook shows up

Actual Result

Nothing shows up

Additional Information

Pesbuk did work like a charm for me for a long while, and suddenly it stopped working. I tried reinstalling it, clearing the cache with UT tweak tool, using different provided site options (touch.facebook, mobile.facebook, etc...) - to no avail. I believe it happened the day Facebook changed its UI (recently) and I can't possibly be the only one experiencing this.

**Comment by kugiigi** [comment]
Can you please attach a screenshot? It is working on my MX4.
The things you can try that I can think of, if you haven't done yet:
- Reboot
- Check if internet is really working
- Try facebook in morph browser

**Comment by Emphrath** [comment]
Rebooting doesn't change anything, and internet works fine. However I just noticed that facebook is unavailable in morph browser:
![screenshot20200724_095616825](https://user-images.githubusercontent.com/53301995/88372174-ae851580-cd95-11ea-8954-9d43d6a09950.png)
I tried disabling uAdBlock (who knows) - doesn't change anything.
Here is what I actually see when I open Pesbuk:
![screenshot20200724_095636486](https://user-images.githubusercontent.com/53301995/88372301-e7bd8580-cd95-11ea-8f55-5e5442f6032a.png)
Whatever buttons I press from there, it sticks to that

**Comment by kugiigi** [comment]
Have you tried in other devices? It's my first time to learn that in other regions, they use a different URL.
Perhaps in your region facebook redirects to fr-fr.facebook.com but that's nor working right now?

**Comment by Emphrath** [comment]
It's the first link in a french search engine. But it's the same with https://m.facebook.com/. Morph can't reach it. I don't own any other device. On a computer, both url work as expected

**Comment by kugiigi** [comment]
I'm sorry but it seems to be an issue that the app cannot fix. The URL works on my phone in Morph although it just redirects to m.facebook.com. Perhaps you can ask someone from France to check if they have the same issue.

**Comment by boriseto** [comment]
I think it's because of the adblock, I can see the same issue mentioned on their app. Some of the sources there actually dissable Facebook.
If the user can confirm you can close this issue.

**Comment by Emphrath** [comment]
Yes indeed I confirm this is UAdBlock related. The incriminated list appears to be "StevenBlack Social Hosts".
Thanks for that, issue closed.
