### ISSUE TITLE
Drag down extends the header of the apl to half screen

### ISSUE THREAD

**Issue by boriseto** [kugiigi/pesbuk-app#21]
-------------------------------------------------------
Bug
-------------------------------------------------------
## Device
- Xperia X
- RC
- Build 14 (I guess)

## Steps to Reproduce
1. Open app...duh

When using desktop view, when scrolling down, the header comes to the middle of screen (screenshot)

5. Close app....necessary? LOL

## Expected Result
Not to drag it there

## Actual Result

![screenshot20201117_133208782](https://user-images.githubusercontent.com/396355/99391719-e0892d00-28da-11eb-91ee-4ca4f99446a7.png)

**Comment by kugiigi** [comment]
This is actually the intended behavior. This happens when you drag down when you are already at the top. Ot will revert back when you drag up again. This is an imitation of Samsung's One UI 😄
