### ISSUE TITLE
Header behavior

### ISSUE THREAD

**Issue by LiohMoeller** [kugiigi/pesbuk-app#34]
When I scroll the feed and press to long, the header extends to a large blue square.

![screenshot20230210_202946546](https://user-images.githubusercontent.com/1267594/218180931-b55e9d8c-f262-4086-a169-0453bd3033c9.png)

**Comment by kugiigi** [comment]
Apologies for this. I will make fix this in the next version and also make this gesture optional and disabled by default. For now, you can swipe up and hold to go back to normal (similar to how you trigger this issue).

**Comment by LiohMoeller** [comment]
That would be great. I still don't understand the intention behind this. What it's useful for?

Swiping back does not work reliable on my device. I now select the About page once I experience the situation.

**Comment by LiohMoeller** [comment]
Have you found some time to address the issue in the meanwhile?

**Comment by kugiigi** [comment]
I'm just finishing on working on my other, where I usually base my features in Pesbuk, then I'll be working on Pesbuk.
In the meantime, I remembered that there's an option to disable this gestures, in the settings, uncheck `Expand header on down swipe`

**Comment by LiohMoeller** [comment]
Great, that works. Thanks!

**Comment by kugiigi** [comment]
Closing this since it was fixed by a setting
